apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  db_host: postgres
  db_user: postgres
  db_name: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  db_password: c2VjcmV0aWs=