apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-crud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-crud
  template:
    metadata:
      labels:
        app: kuber-crud
    spec:
      containers:
        - name: kuber-crud
          image: mosin/kuber-crud:v1
          ports:
            - containerPort: 8080
              name: api
            - containerPort: 9000
              name: management
#          livenessProbe:
#            httpGet:
#              port: management
#              path: /actuator/health
#            initialDelaySeconds: 5
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              port: management
#              path: /actuator/health
#            initialDelaySeconds: 5
#            periodSeconds: 5
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db_user
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db_host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db_name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_password