apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuber-crud-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: kuber-crud-service
                port:
                  number: 8080
